# Generated by Django 4.1.7 on 2025-06-04 16:23

# ESTE DOCUMENTO NO SE MODIFICA
# Despues escribir en la terminal: python manage.py migrate
# con db.sqlite3: es el que ha sido poblado con todos los cambios que acabamos de aplicar
# con las migraciones para visualizarlo se debe abri con la aplicacion de SQLite browser
# despues ir a models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
